# Generated by Django 5.0.7 on 2024-07-18 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traveltrekapp', '0004_hotels_alter_destination_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='hotels',
        ),
    ]
