# Generated by Django 5.0.7 on 2024-07-21 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traveltrekapp', '0006_alter_destination_category_book_now'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_now',
            name='total_price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='destination',
            name='category',
            field=models.CharField(choices=[('adventure', 'adventure'), ('wildlife', 'wildlife'), ('beach', 'beach'), ('religeous', 'religeous'), ('archaeological', 'archaeological'), ('Trek', 'Trek')], max_length=200),
        ),
    ]
